let mapleader=" "
" 代码高亮
syntax on

" 行号设置
set number
" relativenumber选项显示每一行距离当前行的距离
set norelativenumber

set wrap
set showcmd

" 补全指令
set wildmenu

" 搜索相关设置
set hlsearch
exec "nohlsearch"
" 边输入边高亮
set incsearch
" 忽略大小写
set ignorecase
set smartcase

" 设置tab为4空格
set smarttab
set tabstop=2
set shiftwidth=2
set expandtab

" 空格+回车：清楚搜索高亮
noremap <LEADER><CR> :nohlsearch<CR>

" 禁用vim本身错误显示
au ColorScheme * hi Error NONE
au GuiEnter * hi Error NONE

set tags=tags;
set autochdir


set cursorline
" ------------------------------------------------------------------------------
" 其他设置
set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
set mouse=a
set encoding=utf-8
let &t_ut=''
set scrolloff=5
set tw=0
set indentexpr=
set backspace=indent,eol,start
set foldmethod=indent
set foldlevel=99
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
set laststatus=2
set autochdir
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
" ------------------------------------------------------------------------------

" Plug设置------------------------------------------------------
map <C-n> :NERDTreeToggle<CR>
au Filetype FILETYPE let b:AutoPairs = {"(": ")"}
au FileType php      let b:AutoPairs = AutoPairsDefine({'<?' : '?>', '<?php': '?>'})

" Tab插件补全设置
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

" 语法检查插件设置
" Set this in your vimrc file to disabling highlighting
" let g:ale_set_highlights = 0
" let g:ale_set_signs = 0
" LeaderF 设置
let g:Lf_WorkingDirectoryMode = 'AF'
let g:Lf_RootMarkers = ['.git', '.svn', '.hg', '.project', '.root']

" 代码注释插件设置
" Create default mappings
 let g:NERDCreateDefaultMappings = 1

 " Add spaces after comment delimiters by default
 let g:NERDSpaceDelims = 1

 " Use compact syntax for prettified multi-line comments
 let g:NERDCompactSexyComs = 1

 " Align line-wise comment delimiters flush left instead of following code indentation
 let g:NERDDefaultAlign = 'left'

 " Set a language to use its alternate delimiters by default
 let g:NERDAltDelims_java = 1

 " Add your own custom formats or override the defaults
 let g:NERDCustomDelimiters = { 'c': { 'left': '/*','right': '*/'  }, 'cpp': { 'left': '//','right': ''  } }

 " Allow commenting and inverting empty lines (useful when commenting a region)
 let g:NERDCommentEmptyLines = 1

 " Enable trimming of trailing whitespace when uncommenting
 let g:NERDTrimTrailingWhitespace = 1

 " Enable NERDCommenterToggle to check all selected lines is commented or not 
 let g:NERDToggleCheckAllLines = 1

" Plug设置-------------------------------------------------------

" 重新定义普通模式下，键位的功能
map s <nop>
map S :w<CR>
map Q :q<CR>
map R :source $MYVIMRC<CR>

" 分屏 右 左 上 下
map su :set splitright<CR>:vsplit<CR>
map si :set nosplitright<CR>:vsplit<CR>
map so :set nosplitbelow<CR>:split<CR>
map sp :set splitbelow<CR>:split<CR>
" 分屏大小
map <up> :res +5<CR>
map <down> :res -5<CR>
map <left> :vertical resize-5<CR>
map <right> :vertical resize+5<CR>
" 分屏方向改变
map sv <C-w>t<C-w>H
map sh <C-w>t<C-w>K
" 切换分屏
map H <C-w>h
map L <C-w>l
map J <C-w>j
map K <C-w>k

" 标签
map tu :tabe<CR>
" 切换标签 下一个 上一个
map tj :+tabnext<CR>
map tk :-tabnext<CR>

"" 复制粘帖快捷键
"map Y "+y
"map P "+p
" 插件管理
call plug#begin()
  " 下方标题栏
	Plug 'vim-airline/vim-airline'

	" 主题
	Plug 'arcticicestudio/nord-vim'    
	Plug 'altercation/vim-colors-solarized'

  " ls
	Plug 'prabirshrestha/vim-lsp'
	Plug 'mattn/vim-lsp-settings'

  " 文件目录树    
  Plug 'preservim/nerdtree'

  " 模糊匹配插件
  Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }

  "代码补全
  Plug 'maralla/completor.vim'

  " 语法检查
  Plug 'dense-analysis/ale'

  " 括号补全
  Plug 'jiangmiao/auto-pairs'

  " markdown文件预览
  Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown', 'do': 'yarn install'}
  " markdown文件编写
  Plug 'godlygeek/tabular'
  Plug 'preservim/vim-markdown'   

  " 代码注释插件
  Plug 'preservim/nerdcommenter'
call plug#end()

" vim主题设置
color nord

